USE [kay]
GO
/****** Object:  Table [dbo].[F_CORRES_DCT]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_CORRES_DCT](
	[Code_Société] [char](2) NOT NULL,
	[Type_Ident_F] [char](1) NOT NULL,
	[Ident] [int] NOT NULL,
	[Rang_Corr] [int] NOT NULL,
	[Mot_de_Passe] [varchar](100) NULL,
 CONSTRAINT [F_CORRES_DCT_PK] PRIMARY KEY CLUSTERED
(
	[Code_Société] ASC,
	[Type_Ident_F] ASC,
	[Ident] ASC,
	[Rang_Corr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[F_MESS]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_MESS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[status] [char](10) NULL,
	[subject] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FDCT_ARTICLES]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FDCT_ARTICLES](
	[Type_Ident_F] [varchar](100) NOT NULL,
	[Ident] [int] NOT NULL,
	[Séq_Article] [int] NOT NULL,
 CONSTRAINT [FDCT_ARTICLES_PK] PRIMARY KEY CLUSTERED
(
	[Type_Ident_F] ASC,
	[Ident] ASC,
	[Séq_Article] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FMAIL_DCT]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FMAIL_DCT](
	[Code_Société] [char](2) NOT NULL,
	[Type_Ident_F] [char](1) NOT NULL,
	[Ident] [int] NOT NULL,
	[Indice] [int] NOT NULL,
	[Adr_E_Mail] [varchar](100) NULL,
 CONSTRAINT [F_MAIL_DCT_PK] PRIMARY KEY CLUSTERED
(
	[Code_Société] ASC,
	[Type_Ident_F] ASC,
	[Ident] ASC,
	[Indice] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FMAIL_DCT_APPLICATIONS]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FMAIL_DCT_APPLICATIONS](
	[Code_Société] [varchar](100) NOT NULL,
	[Type_Ident_F] [varchar](100) NOT NULL,
	[Ident] [int] NOT NULL,
	[Rang_Corr] [int] NOT NULL,
	[Code_Application] [varchar](100) NOT NULL,
 CONSTRAINT [FMAIL_DCT_APPLICATIONS_PK] PRIMARY KEY CLUSTERED
(
	[Code_Société] ASC,
	[Type_Ident_F] ASC,
	[Ident] ASC,
	[Rang_Corr] ASC,
	[Code_Application] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[K_30]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[K_30](
	[Identifiant] [varchar](100) NOT NULL,
	[Pelli] [bit] NULL,
 CONSTRAINT [K_30_PK] PRIMARY KEY CLUSTERED
(
	[Identifiant] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_ARTICLES]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_ARTICLES](
	[GAMME] [varchar](100) NULL,
	[FAMILLE] [varchar](100) NULL,
	[SOUS_FAMILLE] [varchar](100) NULL,
	[DESIGNATION] [varchar](100) NULL,
	[VISIBLE_WEB] [bit] NULL,
	[SEQ_ARTICLE] [int] IDENTITY(0,1) NOT NULL,
 CONSTRAINT [TAB_ARTICLES_PK] PRIMARY KEY CLUSTERED
(
	[SEQ_ARTICLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_FAM_ARTICLES]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_FAM_ARTICLES](
	[CODE_GAMME] [varchar](100) NOT NULL,
	[CODE_FAMILLE] [varchar](100) NOT NULL,
	[FAMILLE] [varchar](100) NULL,
	[TYPE_ARTICLE] [varchar](100) NULL,
 CONSTRAINT [TAB_FAM_ARTICLES_PK] PRIMARY KEY CLUSTERED
(
	[CODE_GAMME] ASC,
	[CODE_FAMILLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_GAM_ARTICLES]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_GAM_ARTICLES](
	[CODE_GAMME] [varchar](100) NOT NULL,
	[GAMME] [varchar](100) NULL,
	[TYPE_ARTICLE] [varchar](100) NULL,
 CONSTRAINT [TAB_GAM_ARTICLES_PK] PRIMARY KEY CLUSTERED
(
	[CODE_GAMME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_SFAM_ART]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_SFAM_ART](
	[CODE_GAMME] [varchar](100) NOT NULL,
	[CODE_FAMILLE] [varchar](100) NOT NULL,
	[CODE_SOUS_FAMILLE] [varchar](100) NOT NULL,
	[SOUS_FAMILLE] [varchar](100) NULL,
	[TYPE_ARTICLE] [varchar](100) NULL,
 CONSTRAINT [TAB_SFAM_ART_PK] PRIMARY KEY CLUSTERED
(
	[CODE_GAMME] ASC,
	[CODE_FAMILLE] ASC,
	[CODE_SOUS_FAMILLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_TYPE_ARTICLE]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_TYPE_ARTICLE](
	[TYPE_ARTICLE] [varchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAB_WEB_ARTICLES]    Script Date: 10/10/2022 17:17:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAB_WEB_ARTICLES](
	[SEQ_ARTICLE] [int] NOT NULL,
	[TYPE_MAJ] [varchar](100) NULL,
	[DATE_MAJ] [smalldatetime] NULL,
 CONSTRAINT [TAB_WEB_ARTICLES_PK] PRIMARY KEY CLUSTERED
(
	[SEQ_ARTICLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[F_CORRES_DCT] ([Code_Société], [Type_Ident_F], [Ident], [Rang_Corr], [Mot_de_Passe]) VALUES (N'XX', N'C', 123, 1, N'123')
GO
INSERT [dbo].[FDCT_ARTICLES] ([Type_Ident_F], [Ident], [Séq_Article]) VALUES (N'T', 1, 35)
GO
INSERT [dbo].[FDCT_ARTICLES] ([Type_Ident_F], [Ident], [Séq_Article]) VALUES (N'T', 1, 40)
GO
INSERT [dbo].[FMAIL_DCT] ([Code_Société], [Type_Ident_F], [Ident], [Indice], [Adr_E_Mail]) VALUES (N'XX', N'C', 123, 1, N'toto@toto.com')
GO
INSERT [dbo].[FMAIL_DCT_APPLICATIONS] ([Code_Société], [Type_Ident_F], [Ident], [Rang_Corr], [Code_Application]) VALUES (N'XX', N'C', 123, 1, N'DEVWEB')
GO
INSERT [dbo].[K_30] ([Identifiant], [Pelli]) VALUES (N'35.1', 1)
GO
INSERT [dbo].[K_30] ([Identifiant], [Pelli]) VALUES (N'40.1', 1)
GO
SET IDENTITY_INSERT [dbo].[TAB_ARTICLES] ON
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'PER', N'THERMIQUE PERMANENT 1', 1, 0)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'PER', N'THERMIQUE PERMANENT 2', 0, 1)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'PER', N'THERMIQUE PERMANENT 3', 1, 2)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ALI', N'THERMIQUE ALIMENTAIRE 1', 1, 3)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ALI', N'THERMIQUE ALIMENTAIRE 2', 0, 4)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ALI', N'THERMIQUE ALIMENTAIRE 3', 1, 5)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ENL', N'THERMIQUE ENLEVABLE 1', 1, 6)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ENL', N'THERMIQUE ENLEVABLE  2', 0, 7)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'THE', N'ENL', N'THERMIQUE ENLEVABLE  3', 1, 8)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'PER', N'COUCHE PERMANENT 1', 1, 9)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'PER', N'COUCHE PERMANENT 2', 0, 10)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'PER', N'COUCHE PERMANENT 3', 1, 11)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ALI', N'COUCHE ALIMENTAIRE 1', 1, 12)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ALI', N'COUCHE ALIMENTAIRE 2', 0, 13)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ALI', N'COUCHE ALIMENTAIRE 3', 1, 14)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ENL', N'COUCHE ENLEVABLE 1', 1, 15)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ENL', N'COUCHE ENLEVABLE  2', 0, 16)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'COU', N'ENL', N'COUCHE ENLEVABLE  3', 1, 17)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'PER', N'FLUOPERMANENT 1', 1, 18)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'PER', N'FLUOPERMANENT 2', 0, 19)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'PER', N'FLUOPERMANENT 3', 1, 20)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ALI', N'FLUOALIMENTAIRE 1', 1, 21)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ALI', N'FLUOALIMENTAIRE 2', 0, 22)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ALI', N'FLUOALIMENTAIRE 3', 1, 23)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ENL', N'FLUOENLEVABLE 1', 1, 24)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ENL', N'FLUOENLEVABLE  2', 0, 25)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'FLU', N'ENL', N'FLUOENLEVABLE  3', 1, 26)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'MAN', N'76', N'Mandrin 76', 1, 27)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'MAN', N'40', N'Mandrin 40', 1, 28)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'DOR', N'DORC', N'DORURE CHAND 1', 1, 29)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'DOR', N'DORC', N'DORURE CHAND 2', 0, 30)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'DOR', N'DORC', N'DORURE CHAND 3', 1, 31)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'DOR', N'DORF', N'DORURE FROID 1', 1, 32)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'DOR', N'DORF', N'DORURE FROID 2', 0, 33)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'VER', N'NC', N'VERNIS 1', 1, 34)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'PER', N'PP PER 1', 1, 35)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'VER', N'NC', N'VERNIS 2', 0, 36)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'MP', N'VER', N'NC', N'VERNIS 3', 1, 37)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'PER', N'PP PER 2', 1, 38)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'PER', N'PP PER 3', 1, 39)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'ENL', N'PP  ENL 1', 1, 40)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'ENL', N'PP ENL  2', 1, 41)
GO
INSERT [dbo].[TAB_ARTICLES] ([GAMME], [FAMILLE], [SOUS_FAMILLE], [DESIGNATION], [VISIBLE_WEB], [SEQ_ARTICLE]) VALUES (N'SUP', N'PP', N'ENL', N'PP ENL 3', 1, 42)
GO
SET IDENTITY_INSERT [dbo].[TAB_ARTICLES] OFF
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'DOR', N'Dorure', NULL)
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'MAN', N'Mandrins', N'MAN')
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'VER', N'Vernis', N'VER')
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'COU', N'COUCHE', NULL)
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'FLU', N'FLUO', NULL)
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'PP', N'PP', NULL)
GO
INSERT [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE], [FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'THE', N'THERMIQUE', NULL)
GO
INSERT [dbo].[TAB_GAM_ARTICLES] ([CODE_GAMME], [GAMME], [TYPE_ARTICLE]) VALUES (N'MP', N'Matière première', NULL)
GO
INSERT [dbo].[TAB_GAM_ARTICLES] ([CODE_GAMME], [GAMME], [TYPE_ARTICLE]) VALUES (N'SUP', N'Supports', N'SUP')
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'DOR', N'DORC', N'DORRURE A CHAND', N'DORC')
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'DOR', N'DORF', N'DORRURE A FROID', N'DORF')
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'MAN', N'40', N'DIAMETRE 40', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'MAN', N'76', N'DIAMETRE 76', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'MP', N'VER', N'NC', N'Non Classé', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'COU', N'ALI', N'ALIMENTAIRE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'COU', N'ENL', N'ENLEVABLE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'COU', N'PER', N'PERMANENT', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'FLU', N'ALI', N'ALIMENTAIRE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'FLU', N'ENL', N'ENLEVABLE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'FLU', N'PER', N'PERMANENT', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'PP', N'ALI', N'ALIMENTAIRE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'PP', N'ENL', N'ENLEVABLE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'PP', N'PER', N'PERMANENT', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'THE', N'ALI', N'ALIMENTAIRE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'THE', N'ENL', N'ENLEVABLE', NULL)
GO
INSERT [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE], [SOUS_FAMILLE], [TYPE_ARTICLE]) VALUES (N'SUP', N'THE', N'PER', N'PERMANENT', NULL)
GO
ALTER TABLE [dbo].[TAB_ARTICLES]  WITH CHECK ADD  CONSTRAINT [TAB_ARTICLES_FK] FOREIGN KEY([GAMME], [FAMILLE], [SOUS_FAMILLE])
REFERENCES [dbo].[TAB_SFAM_ART] ([CODE_GAMME], [CODE_FAMILLE], [CODE_SOUS_FAMILLE])
GO
ALTER TABLE [dbo].[TAB_ARTICLES] CHECK CONSTRAINT [TAB_ARTICLES_FK]
GO
ALTER TABLE [dbo].[TAB_FAM_ARTICLES]  WITH CHECK ADD  CONSTRAINT [TAB_FAM_ARTICLES_FK] FOREIGN KEY([CODE_GAMME])
REFERENCES [dbo].[TAB_GAM_ARTICLES] ([CODE_GAMME])
GO
ALTER TABLE [dbo].[TAB_FAM_ARTICLES] CHECK CONSTRAINT [TAB_FAM_ARTICLES_FK]
GO
ALTER TABLE [dbo].[TAB_SFAM_ART]  WITH CHECK ADD  CONSTRAINT [TAB_SFAM_ART_FK] FOREIGN KEY([CODE_GAMME], [CODE_FAMILLE])
REFERENCES [dbo].[TAB_FAM_ARTICLES] ([CODE_GAMME], [CODE_FAMILLE])
GO
ALTER TABLE [dbo].[TAB_SFAM_ART] CHECK CONSTRAINT [TAB_SFAM_ART_FK]
GO
ALTER TABLE [dbo].[TAB_WEB_ARTICLES]  WITH CHECK ADD  CONSTRAINT [TAB_WEB_ARTICLES_FK] FOREIGN KEY([SEQ_ARTICLE])
REFERENCES [dbo].[TAB_ARTICLES] ([SEQ_ARTICLE])
GO
ALTER TABLE [dbo].[TAB_WEB_ARTICLES] CHECK CONSTRAINT [TAB_WEB_ARTICLES_FK]
GO
