
name: unti tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "api/**"

jobs:
  unit-tests:
    defaults:
        run:
          shell: bash
          working-directory: api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # Install dependencies
      - name: yarn install
        run: |
            yarn config set enableGlobalCache false
            yarn install

      # Build
      - run: yarn test:unit
